# CMake generated Testfile for 
# Source directory: E:/B/MITK-superbuild/ep/src/DCMTK/ofstd/tests
# Build directory: E:/B/MITK-superbuild/ep/src/DCMTK-build/ofstd/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ofstd_OFCharacterEncoding_1 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFCharacterEncoding_1")
set_tests_properties(ofstd_OFCharacterEncoding_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_2 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFCharacterEncoding_2")
set_tests_properties(ofstd_OFCharacterEncoding_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_3 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFCharacterEncoding_3")
set_tests_properties(ofstd_OFCharacterEncoding_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_4 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFCharacterEncoding_4")
set_tests_properties(ofstd_OFCharacterEncoding_4 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_5 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFCharacterEncoding_5")
set_tests_properties(ofstd_OFCharacterEncoding_5 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_6 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFCharacterEncoding_6")
set_tests_properties(ofstd_OFCharacterEncoding_6 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_7 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFCharacterEncoding_7")
set_tests_properties(ofstd_OFCharacterEncoding_7 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFCharacterEncoding_8 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFCharacterEncoding_8")
set_tests_properties(ofstd_OFCharacterEncoding_8 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFDate "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFDate")
set_tests_properties(ofstd_OFDate PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFDateTime "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFDateTime")
set_tests_properties(ofstd_OFDateTime PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFList_1 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFList_1")
set_tests_properties(ofstd_OFList_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFList_2 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFList_2")
set_tests_properties(ofstd_OFList_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFList_splice "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFList_splice")
set_tests_properties(ofstd_OFList_splice PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFMap "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFMap")
set_tests_properties(ofstd_OFMap PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStack "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFStack")
set_tests_properties(ofstd_OFStack PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFStandard_isReadWriteable "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFStandard_isReadWriteable")
set_tests_properties(ofstd_OFStandard_isReadWriteable PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFFile "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFFile")
set_tests_properties(ofstd_OFFile PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_compare "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFString_compare")
set_tests_properties(ofstd_OFString_compare PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_concatenate "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFString_concatenate")
set_tests_properties(ofstd_OFString_concatenate PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_constructor "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFString_constructor")
set_tests_properties(ofstd_OFString_constructor PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_identity_1 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFString_identity_1")
set_tests_properties(ofstd_OFString_identity_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_identity_2 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFString_identity_2")
set_tests_properties(ofstd_OFString_identity_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_identity_3 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFString_identity_3")
set_tests_properties(ofstd_OFString_identity_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_reserve "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFString_reserve")
set_tests_properties(ofstd_OFString_reserve PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFString_substr "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFString_substr")
set_tests_properties(ofstd_OFString_substr PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFTime "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFTime")
set_tests_properties(ofstd_OFTime PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFUUID_1 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFUUID_1")
set_tests_properties(ofstd_OFUUID_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFUUID_2 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFUUID_2")
set_tests_properties(ofstd_OFUUID_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_OFVector "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_OFVector")
set_tests_properties(ofstd_OFVector PROPERTIES  LABELS "ofstd")
add_test(ofstd_atof "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_atof")
set_tests_properties(ofstd_atof PROPERTIES  LABELS "ofstd")
add_test(ofstd_base64_1 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_base64_1")
set_tests_properties(ofstd_base64_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_base64_2 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_base64_2")
set_tests_properties(ofstd_base64_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_base64_3 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_base64_3")
set_tests_properties(ofstd_base64_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_ftoa "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_ftoa")
set_tests_properties(ofstd_ftoa PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_1 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_markup_1")
set_tests_properties(ofstd_markup_1 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_2 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_markup_2")
set_tests_properties(ofstd_markup_2 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_3 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_markup_3")
set_tests_properties(ofstd_markup_3 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_4 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_markup_4")
set_tests_properties(ofstd_markup_4 PROPERTIES  LABELS "ofstd")
add_test(ofstd_markup_5 "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_markup_5")
set_tests_properties(ofstd_markup_5 PROPERTIES  LABELS "ofstd")
add_test(ofstd_testPaths "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_testPaths")
set_tests_properties(ofstd_testPaths PROPERTIES  LABELS "ofstd")
add_test(ofstd_thread "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_thread")
set_tests_properties(ofstd_thread PROPERTIES  LABELS "ofstd")
add_test(ofstd_xmlParser "E:/B/MITK-superbuild/ep/src/DCMTK-build/bin/ofstd_tests" "ofstd_xmlParser")
set_tests_properties(ofstd_xmlParser PROPERTIES  LABELS "ofstd")
