set(ITKIOIPL_LOADED 1)
set(ITKIOIPL_DEPENDS "ITKIOImageBase")
set(ITKIOIPL_LIBRARIES "ITKIOIPL")
set(ITKIOIPL_INCLUDE_DIRS "E:/B/MITK-superbuild/ep/src/ITK/Modules/IO/IPL/include")
set(ITKIOIPL_LIBRARY_DIRS "")

