set(ITKIOMRC_LOADED 1)
set(ITKIOMRC_DEPENDS "ITKIOImageBase")
set(ITKIOMRC_LIBRARIES "ITKIOMRC")
set(ITKIOMRC_INCLUDE_DIRS "E:/B/MITK-superbuild/ep/src/ITK/Modules/IO/MRC/include")
set(ITKIOMRC_LIBRARY_DIRS "")

